baseURL = 'http://www.liangtao.cc'
languageCode = 'zh-cn'
title = "Jimmy's Blog"
theme = 'paper'


[params]
github = "jimmyrogue"
avatar = 'http://qiniu.ysjf.com/%E4%B8%8B%E8%BD%BD.png'                 # gravatar email or image url
name = 'Tao Liang'
bio = '这里就是罗德岛，要跳就在这里跳'

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 10
